name: ciccd_task_2
run-name: ${{ github.actor }} - ${{ github.sha }}

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

env:
  PYTHON_VARIABLE: "3.8"

jobs:
  python-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VARIABLE }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VARIABLE }}

      - name: Install dependencies
        working-directory: src
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest coverage
          pip install -r src/requirements.txt

      - name: Run tests
        working-directory: src
        run: |
          pytest

      - name: Generate coverage
        working-directory: src
        run: |
          coverage run -m pytest

      - name: Show coverage report
        working-directory: src
        run: |
          coverage report -m

      - name: Check code style (flake8)
        continue-on-error: true
        working-directory: src
        run: |
          flake8 .

      - name: Check code complexity
        continue-on-error: true
        working-directory: src
        run: |
          flake8 . --max-complexity=10

      - name: Upload python source code
        uses: actions/upload-artifact@v4
        with:
          name: python-source-code
          path: |
            src/**/*.py
